### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by idougwarner** [ambientlight/amplify-cli-action#19]
Github actions throw the following error once it starts `to` publish.

**An error occurred during the publish operation: Invalid config undefined**

I could publish from my local terminal though. My local amplify version is 4.43.0

The action script is

jobs:
  deploy:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Configure Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:dev
      - name: Deploy
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: publish
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

Can you advise me on how to get this fixed?

**Comment by SimonHoiberg** [comment]
Most likely the same issue is [this one](https://github.com/ambientlight/amplify-cli-action/issues/16).

**Comment by tobocop2** [comment]
I've made a fix here, and am able to successfully publish with the latest amplify now:

#23

**Comment by ambientlight** [comment]
Closed by #23 and available in [0.2.2](https://github.com/ambientlight/amplify-cli-action/releases/tag/0.2.2)
