### ISSUE TITLE
Amplify headless docs

### ISSUE THREAD

**Issue by nino-moreton** [ambientlight/amplify-cli-action#4]
After trying to use the amplify headless method for CI / CD and following the [docs](https://aws-amplify.github.io/docs/cli-toolchain/usage#headless-mode), I'm gonna try this out. 

I was just wondering if you also tried to first follow the docs as well? I noticed that you're configuring / initializing the Amplify env by basically creating the `local-env-info.json` .. In my experience with the recommend way in docs, setting credentials inside `providers` and providing `AWSCLOUDFORMATIONCONFIG` never really worked. (for amplify init and pull). 

Anyway thanks for this. Just wanted to know if you've had the same experience.

**Comment by ambientlight** [comment]
there was an issue with on `amplify-cli` side previous(not sure if still), so `local-env-info.json` was required (it is in .gitignore by default).

The configuring / initializing of amplify env is done via `amplify env pull --yes`

Is there any specific issue you run into?

**Comment by nino-moreton** [comment]
Not with amplify-cli-action (been using it now in our CI / CD and works great!) but with the amplify-cli. It just doesn't seem to accept the `useProfile` boolean. Even when I'm setting it to false, it keeps on erroring out looking for the `~/.aws/credential` path (which of course doesn't exist inside the ci / cd pipeline.

I think line 62 in your entrypoint.sh
```bash
echo '{"projectPath": "'"$(pwd)"'","defaultEditor":"code","envName":"'$6'"}' > ./amplify/.config/local-env-info.json
```

is what makes `amplify env pull --yes` works. Instead of what's recommended in the docs, which is to pass in stringified JSON args in a bash script like so:
```bash
amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```

I'll definitely open an issue over at @aws/amplify-cli now. I just wanted to confirm with you first if you ran into the same issue that I had. Thanks!
