### ISSUE TITLE
Amplify publish error

### ISSUE THREAD

**Issue by juunone** [ambientlight/amplify-cli-action#8]
![스크린샷 2020-04-06 20 42 56](https://user-images.githubusercontent.com/35126809/78555147-5dcdc900-7847-11ea-9707-e26fc0e5bd4d.png)

hi i want to publish with amplify to cloud front
but it seems Failed at the amplify-dynamodb-simulator@0.5.0 install script.
i don't know how to solve this problem.
i will wait answer, thank you

**Comment by ambientlight** [comment]
@juunone: hi, let me know which version of amplify are you on? (you should see amplify version logged in your github actions output)

**Comment by juunone** [comment]
@ambientlight hi thanks to reply
```
uses: ambientlight/amplify-cli-action@0.2.1
frontend: javascript
framework: 'react'
build_command: 'npm run build'
amplify_cli_version: '3.0'
amplify_command: publish
amplify_arguments: '-c'
amplify_env: rnd
```
my amplify version is 3.0

**Comment by ambientlight** [comment]
@juunone: hm, `amplify-dynamodb-simulator` failing to install in CI environment might be to various reasons, I am personally not familiar with it to give you any immediate feedback.

This action is based on `node:10` container image from https://hub.docker.com/_/node/ which should be based on alpine-linux, I am not sure if this is somehow the source of the issue, you might need to get into those generated logs, or try reproducing `amplify-dynamodb-simulator` installation in your custom docker image based on `node:10` to debug I guess

using of `amplify-dynamodb-simulator` in CI should be a common usecase, will try to investigate soon

**Comment by juunone** [comment]
i solved this problem with `amplify_cli_version`
maybe it depends on cli version, i'm modified version to   `amplify_cli_version: '3.17.0'`

but i have one more problem with this screen shot
i have already configure my amplify env but this issue happening with my publich command.
![스크린샷 2020-04-07 10 47 49](https://user-images.githubusercontent.com/35126809/78621295-416c7380-78bd-11ea-8f3d-964dfce123b9.png)

**Comment by ambientlight** [comment]
@juunone: are you specifying a custom `project_dir` (`project_dir` is available as step parameter, it should be set to a folder that contains `amplify/`) ?

by default step assumes `amplify/` is available in the root of your repo

**Comment by juunone** [comment]
sorry i missed my yml
i have deploy another job this env than env init is not settings already
i solved with merge that jobs and share envs.
thank you for answer.
